FROM golang:1.13-alpine3.10 as build
ENV GO111MODULE=on
WORKDIR /go/src/app
COPY . .
RUN apk add --no-cache --update build-base git && \
    GOOS=linux GOARCH=__GOLANG_ARCH__ make build

FROM __BASEIMAGE_ARCH__/alpine:3.10
RUN apk add --no-cache --update ca-certificates
COPY --from=build /go/src/app/unifi2mqtt /usr/local/bin/unifi2mqtt
CMD ["unifi2mqtt"]
