// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/mannkind/paho.mqtt.golang.ext/cfg"
	"github.com/mannkind/paho.mqtt.golang.ext/di"
)

// Injectors from wire.go:

func Initialize() *Unifi2Mqtt {
	mqttConfig := cfg.NewMQTTConfig()
	config := NewConfig(mqttConfig)
	mqttFuncWrapper := di.NewMQTTFuncWrapper()
	unifi2Mqtt := NewUnifi2Mqtt(config, mqttFuncWrapper)
	return unifi2Mqtt
}
